# Generated by Django 5.0.7 on 2024-11-22 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IFA',
            fields=[
                ('id_IFA', models.AutoField(primary_key=True, serialize=False)),
                ('lote', models.CharField(max_length=255, unique=True)),
                ('fecha_fabricacion', models.DateField()),
                ('volumen', models.CharField(max_length=255)),
                ('act_biologica', models.CharField(max_length=255)),
                ('act_espectral', models.CharField(max_length=255)),
                ('prot_total', models.CharField(max_length=255)),
                ('act_total_UT', models.CharField(max_length=255)),
                ('existencia_UT', models.CharField(max_length=255)),
                ('existencia_vol_IFA', models.CharField(max_length=255)),
                ('vol_form_liquido', models.CharField(max_length=255)),
                ('dosis_esperadas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formulacion',
            fields=[
                ('id_orden_formulacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('vol_teorico', models.CharField(max_length=255)),
                ('fecha_fab', models.DateField()),
                ('fecha_vence', models.DateField()),
                ('consumo_IFA_UT', models.CharField(max_length=255)),
                ('frascos_esperados', models.CharField(max_length=255)),
                ('id_IFA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIGB.ifa')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_materiales', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIGB.producto')),
            ],
        ),
        migrations.AddField(
            model_name='ifa',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIGB.producto'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=255, verbose_name='apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('cargo', models.CharField(max_length=255, verbose_name='cargo')),
                ('tipo', models.CharField(max_length=255, verbose_name='tipo')),
                ('usuario', models.CharField(max_length=255, unique=True, verbose_name='usuario')),
                ('contraseña', models.CharField(max_length=255, verbose_name='contraseña')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='CIGB.producto')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('presentacion', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('firma', models.CharField(max_length=255)),
                ('cantidad_solicitada', models.IntegerField()),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField()),
                ('cantidad_pendiente', models.IntegerField(null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIGB.producto')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Llenado',
            fields=[
                ('id_orden_llenado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('fecha_llenado', models.DateField()),
                ('cantidad_llenada', models.CharField(max_length=255)),
                ('cantidad_revisada', models.CharField(max_length=255)),
                ('existencias_llenada', models.CharField(max_length=255)),
                ('observaciones', models.TextField()),
                ('id_orden_formulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIGB.formulacion')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ifa',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulacion',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Envase',
            fields=[
                ('id_orden_envase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('fecha_envase', models.DateField()),
                ('cantidad_envasar', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('fecha_liberada', models.DateField()),
                ('cantidad_liberada', models.CharField(max_length=255)),
                ('exist_liberada', models.CharField(max_length=255)),
                ('observaciones', models.TextField()),
                ('id_orden_llenado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIGB.llenado')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_entregada', models.IntegerField()),
                ('fecha_entrega', models.DateField()),
                ('id_orden_envase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIGB.envase')),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIGB.solicitud')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
