# Generated by Django 5.0.7 on 2024-11-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CIGB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envase',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='llenado',
            name='observaciones',
        ),
    ]
